# Generated by Django 3.2.9 on 2021-12-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_shop_telephone2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-id']},
        ),
    ]
