# Generated by Django 3.2.9 on 2021-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hyeonil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=100, verbose_name='게임명')),
                ('gamedate', models.DateField(verbose_name='플레이 날짜')),
                ('clear', models.BooleanField(verbose_name='클리어 여부')),
                ('gold', models.CharField(max_length=100, verbose_name='획득골드')),
            ],
        ),
    ]
