# Generated by Django 3.2.9 on 2021-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyeonilapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyeonil',
            name='gamedate',
            field=models.DateTimeField(verbose_name='플레이 날짜'),
        ),
    ]
